export const FETCH_PROD_TYPES='FETCH_PROD_TYPES'

export const FETCH_SPECIFIC_TYPE='FETCH_SPECIFIC_TYPE'

export const FILTER_BY_SEARCH='FILTER_BY_SEARCH'

export const FILTER_PRODUCT_BY_TYPE = 'FILTER_PRODUCT_BY_TYPE'